language: python
sudo: false
python: "3.6"

branches:
  only:
    - develop
    - master

cache:
  - pip: true
  - directories:
      - $PIP_CACHE_DIR

env:
  global:
    - MAIN_CMD="pytest"
    - SETUP_CMD="mdbenchmark -v"
    - CONDA_DEPENDENCIES="datreant jinja2 click==6.7 pandas matplotlib xdg<2"
    - CONDA_CHANNELS="conda-forge"
    - NUMPY_VERSION=stable
    - PIP_CACHE_DIR=$HOME/.cache/pip
    - CODECOV=""
    - PYTEST_COV=""
    - UPGRADE_PIP="pip install --upgrade pip"

jobs:
  include:
    - stage: "Linux - Unit tests"
      name: "Python 3.6"
      env:
        - CODECOV="--cov mdbenchmark"
        - PYTEST_COV="pytest-cov codecov"
    - name: "Python 3.7"
      language: python
      python: 3.7
      dist: xenial
      sudo: true
    - name: "Python 3.5"
      python: "3.5"
    - name: "Python 2.7"
      python: "2.7"

    - stage: "Linting and formatting"
      name: "Formatting with black"
      install:
        - $UPGRADE_PIP
        - pip install black
      script: make reformat-check
    - name: "Linting with flake8"
      install:
        - $UPGRADE_PIP
        - pip install flake8
      script: make flake8
    - name: "Sorting with isort"
      install:
        - $UPGRADE_PIP
        - pip install isort
      script: make isort-check
    - name: "Lint reStructuredText"
      install:
        - $UPGRADE_PIP
        - pip install restructuredtext_lint
      script: make rst-lint
    - name: "Try to build documentation"
      install:
        - $UPGRADE_PIP
        - pip install . sphinx-click
      script: python setup.py build_sphinx

    - stage: "macOS - Unit tests"
      language: generic
      name: "Python 2.7"
      env: PYTHON_VERSION=2.7
      install:
        - git clone git://github.com/astropy/ci-helpers.git
        - source ci-helpers/travis/setup_conda.sh
        - pip install -e .
      script: $MAIN_CMD $SETUP_CMD

install:
  - $UPGRADE_PIP
  - pip install . $PYTEST_COV

script:
  - pytest $CODECOV

after_success:
  - if [ -z ${CODECOV} ]; then echo "Skipping codecov submit"; else codecov; fi
